Table
SergeyOdnosteblets/test-task-ts pull request #12
Opened 2022-09-20 06:38 UTC by SergeyOdnosteblets

2022-09-20 07:53 UTC, t-shevchuk approved these changes

2022-09-20 11:11 UTC, t-shevchuk requested changes

2022-09-20 11:11 UTC, t-shevchuk commented on src/App.tsx
> +                sortUsers={sortUsers}
naming for both

2022-09-20 11:11 UTC, t-shevchuk commented on src/components/Filter/Filter.tsx
> +        <form onSubmit={handleSubmit(onSubmit) } >
formatting

2022-09-20 11:11 UTC, t-shevchuk commented on src/components/List/List.module.scss.d.ts
> +export const table:string
format this file

2022-09-20 11:11 UTC, t-shevchuk commented on src/components/List/List.tsx
> +    if (sortUsers) {
not obvious naming

2022-09-20 11:11 UTC, t-shevchuk commented on src/components/List/List.tsx
> +  const handleTableFilter = (id: string | number) => {
You don't handle filtering here

2022-09-20 11:11 UTC, t-shevchuk commented on src/pages/ListContainer/ListContainer.tsx
> +          firlteredUsers={firlteredUsers}
typo `filtered`

2022-09-20 11:11 UTC, t-shevchuk commented on src/pages/ListContainer/ListContainer.tsx
> +              alert('faildToAddCount');
typo `failed`

2022-09-20 11:11 UTC, t-shevchuk commented on src/pages/ListContainer/ListContainer.tsx
> +      </div>
Why in this PR are old changes? that should be merged and new branch should have the last sources

2022-09-21 13:42 UTC, t-shevchuk commented on src/components/List/List.tsx
> +  const sortBy = (category: string | number) => {
onSortingChange

2022-09-21 13:43 UTC, t-shevchuk commented on src/App.tsx
> +  const [filteredUsers, setFilteredUsers] = useState<UserInfo[]>(list);
Why do you need it here?

2022-09-21 13:44 UTC, t-shevchuk commented on src/App.tsx
> +  const [forceRefresh, setForceRefresh] = useState(true);
why?

2022-09-21 13:44 UTC, t-shevchuk commented on src/components/List/List.tsx
> +  sortCategory,
sortBy, setSortBy

2022-09-21 13:44 UTC, t-shevchuk commented on src/components/List/List.tsx
> +      console.log('rerender');
remove

2022-09-21 13:47 UTC, t-shevchuk commented on src/types/ListTypes.ts
> +    setSortCategory: React.Dispatch<React.SetStateAction<string | number>>
you don't use dispatch in your project. that's just a function

2022-09-21 13:47 UTC, t-shevchuk commented on src/types/UserListItemProps.ts
> +    setSortCategory: React.Dispatch<React.SetStateAction<string | number>>
same here

2022-09-21 13:47 UTC, t-shevchuk commented on src/types/UserToEdit.ts
>      setIsModalActive: React.Dispatch<React.SetStateAction<boolean>>
and here

2022-09-21 14:04 UTC, SergeyOdnosteblets commented on src/App.tsx
> +  const [filteredUsers, setFilteredUsers] = useState<UserInfo[]>(list);
changed

2022-09-21 14:04 UTC, SergeyOdnosteblets commented on src/App.tsx
> +  const [forceRefresh, setForceRefresh] = useState(true);
changed

2022-09-21 15:33 UTC, t-shevchuk commented on src/components/Filter/Filter.tsx
> +        <form onSubmit={handleSubmit(onSubmit)} >
formatting

2022-09-21 15:34 UTC, t-shevchuk commented on src/components/List/List.module.scss
> +
formatting

2022-09-21 15:43 UTC, merged